all:
  hosts:
    node1:
      ansible_host: 159.223.224.118
      ip: 159.223.224.118
      access_ip: 159.223.224.118
    node2:
      ansible_host: 134.209.83.44
      ip: 134.209.83.44
      access_ip: 134.209.83.44
    node3:
      ansible_host: 134.209.91.168
      ip: 134.209.91.168
      access_ip: 134.209.91.168
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
