all:
  hosts:
    node1:
      ansible_host: 167.172.42.3
      ip: 167.172.42.3
      access_ip: 167.172.42.3
    node2:
      ansible_host: 146.190.234.64
      ip: 146.190.234.64
      access_ip: 146.190.234.64
    node3:
      ansible_host: 164.92.144.48
      ip: 164.92.144.48
      access_ip: 164.92.144.48
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
